### ISSUE TITLE
Support React 0.14

### ISSUE THREAD

**Issue by zallek** [botify-labs/react-classmap#3]

**Comment by alexkirsz** [comment]
All tests run fine on react@0.14.0-alpha1, but [the roadmap to 0.14](https://github.com/facebook/react/issues/3220) includes changes that will break the current implementation.

`react-classmap` hooks into `ReactCompositeComponent::_processProps` to alter props processing for DOM components only, but as per [this issue](https://github.com/facebook/react/issues/3223), DOM components won't be wrapped in `ReactCompositeComponent` anymore, so we'll need to find another way.

My first attempt at implementing this was to hook into the markup generation and dom diffing algorithms of React, which is far more complex but less likely to disappear.

Another idea was to hook into `React.createElement`, but since elements can be hoisted out of render there's no way to consistently retrieve parent context.

It might also be possible to implement the same functionality by cloning elements in `ReactReconciler.{mountComponent,receiveComponent}`.

**Comment by zallek** [comment]
done with https://github.com/botify-labs/react-classmap/pull/6
